// <auto-generated />
namespace WebBanHangOnlines.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ImpactModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImpactModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202403301200002_ImpactModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
